"""update tabel user

Revision ID: 0666166cb459
Revises: 1a85e44784e8
Create Date: 2022-03-01 22:16:27.707847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0666166cb459'
down_revision = '1a85e44784e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_user', sa.BigInteger(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_foreign_key(None, 'user', 'akun', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('user', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'id_user')
    # ### end Alembic commands ###
