"""membuat tabel user

Revision ID: 0ec928e84e70
Revises: 
Create Date: 2022-03-01 15:21:59.924315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ec928e84e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('makanan')
    op.drop_table('resep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resep',
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bahan_bahan', mysql.TEXT(), nullable=False),
    sa.Column('langkah', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_resep'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('makanan',
    sa.Column('id_makanan', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_makanan', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('air', mysql.FLOAT(), nullable=False),
    sa.Column('energi', mysql.FLOAT(), nullable=False),
    sa.Column('protein', mysql.FLOAT(), nullable=False),
    sa.Column('lemak', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('karbo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('serat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('abu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kalsium', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fosfor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('besi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('natrium', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kalium', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tembaga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('seng', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('retinol', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('b_kar', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kar_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('thiamin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('riboflavin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('niasin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('vit_c', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bdd', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kategori', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('jenis_bahan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_resep'], ['resep.id_resep'], name='id_resep'),
    sa.PrimaryKeyConstraint('id_makanan'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
