"""update tabel user lagi lagi

Revision ID: 1b045f333ba3
Revises: ceda45c70338
Create Date: 2022-03-01 22:41:19.342475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b045f333ba3'
down_revision = 'ceda45c70338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('c_makanan', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'c_makanan')
    # ### end Alembic commands ###
