"""membuat tabel user

Revision ID: 3c9a442dd5ce
Revises: 0ec928e84e70
Create Date: 2022-03-01 15:26:49.391928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9a442dd5ce'
down_revision = '0ec928e84e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('aktivitas_fisik', sa.Integer(), nullable=False),
    sa.Column('riwayat_penyakit', sa.String(length=20), nullable=False),
    sa.Column('pref_bahan', sa.String(length=250), nullable=False),
    sa.Column('bmr', sa.Float(), nullable=False),
    sa.Column('jumlah_kalori_per_hari', sa.Float(), nullable=False),
    sa.Column('sisa_kalori', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
