"""buat user

Revision ID: dd466e783bf6
Revises: 1b045f333ba3
Create Date: 2022-03-03 17:50:16.313691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd466e783bf6'
down_revision = '1b045f333ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=2), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('aktivitas_fisik', sa.Integer(), nullable=False),
    sa.Column('riwayat_penyakit', sa.String(length=20), nullable=False),
    sa.Column('c_makanan', sa.String(length=250), nullable=False),
    sa.Column('pref_bahan', sa.String(length=250), nullable=False),
    sa.Column('bmr', sa.Float(), nullable=False),
    sa.Column('jumlah_kalori_per_hari', sa.Float(), nullable=False),
    sa.Column('sisa_kalori', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['akun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('makanan', 'no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('makanan', sa.Column('no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('user')
    # ### end Alembic commands ###
